### ISSUE TITLE
Unclear how the dataset is downloaded

### ISSUE THREAD

**Issue by balaneshin** [khcs/learning-to-read#1]
It is mentioned in the README file that:

"Dataset can be downloaded from the Open-i chest x-ray subset (link)"

However, from the provided link, it is not clear how the dataset is downloaded. Can you please elaborate this?

**Comment by balaneshin** [comment]
The dataset can be obtained by contacting [openi.nlm.nih.gov](https://openi.nlm.nih.gov./contactus.php).

**Comment by khcs** [comment]
It can also be downloaded using the RESTful API:
https://openi.nlm.nih.gov./services.php?it=xg

Sorry for the late reply!
