### ISSUE TITLE
Unclear how to generate annotation

### ISSUE THREAD

**Issue by ahsanp** [khcs/learning-to-read#2]
I was able the perform all the training stages and run the generate_data and main file. But I am unclear as to how to generate annotation for any other x-rays which I might have.

Any help would be highly appreciated. Thanks

**Comment by khcs** [comment]
The MeSH annotations were generated manually, as noted in the paper.
Perhaps https://github.com/kilicogluh/Bio-SCoRes could be a starting point to look at to work towards automatic MeSH annotation generation.

**Comment by ahsanp** [comment]
I am sorry I didn't pose the question correctly. I understand that the training data (MeSH annotations) was generated manually. I actually wanted to know how can I use your code to predict annotations for any other x-ray image which I might have.
Sorry for the misunderstanding.

**Comment by khcs** [comment]
In that case, I would have a list of 'image file name' - 'MeSH annotation' pairs in a file like in data/chestx/MeSH/original, put the images in data/chestx/ims, and follow the same procedure as in the provided source code.

**Comment by wanghaisheng** [comment]
@AhsanPervaizAnjum  can you give me a little more detailed steps about "perform all the training stages and run the generate_data and main file."
