### ISSUE TITLE
Dataset can't be downloaded

### ISSUE THREAD

**Issue by shengwa** [khcs/learning-to-read#4]
Hi,

I found the dataset couldn't be downloaded, is it possible to fix this?

**Comment by khcs** [comment]
I download the dataset using the Open-i API:
https://openi.nlm.nih.gov/services.php?it=xg

With the popularity of the dataset and many enquiries, I see they now provide a direct link to download the data:
https://openi.nlm.nih.gov/faq.php?it=xg

**Comment by shengwa** [comment]
Thanks for the links, they help a lot!
